Description: solutions to Tasks 1 - 4 of tAPP 4

Version: 1.0.2.20210122

Author: Arvin Zhao

Last editors: Arvin Zhao

(Python 3.8.5 + NumPy 1.19.5)

# Task 1

In [1]:
import numpy as np


print(np.arange(10, 21))  # Create a NumPy array of the integers from 10 to 20.

[10 11 12 13 14 15 16 17 18 19 20]


# Task 2

In [2]:
# import numpy as np


who_knows = np.arange(9).reshape(3, 3)  # Create a 3x3 NumPy array of the integers from 0 to 8.
print(who_knows)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [3]:
file_name = 'task2.txt'

np.savetxt(file_name, who_knows, fmt = '%d')
print(np.loadtxt(file_name, dtype = int))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


----------

It has been agreed that there are at least 4 ways to calculate the **matrix** product of the NumPy **arrays** `array1` and `array2` in the following tasks.

- [`np.matmul(array1, array2)`](https://numpy.org/doc/stable/reference/generated/numpy.matmul.html)

- [`np.dot(array1, array2)`](https://numpy.org/doc/stable/reference/generated/numpy.dot.html)

- [`array1 @ array2`](https://www.python.org/dev/peps/pep-0465/)

- `np.matrix(array1) * np.matrix(array2)`

# Task 3

In [6]:
# import numpy as np


array1 = np.array([
    [23, 45, 11],
    [12, 23, 54],
    [1, 23, 10]
])
array2 = np.array([
    [3, 5, 1],
    [2, 3, 4],
    [9, 1, 5]
])

print('Addition:')
print(array1 + array2)
print('\nSubtraction:')
print(array1 - array2)
print('\nMatrix product:')
print(np.matmul(array1, array2))

Addition:
[[26 50 12]
 [14 26 58]
 [10 24 15]]

Subtraction:
[[20 40 10]
 [10 20 50]
 [-8 22  5]]

Matrix product:
[[258 261 258]
 [568 183 374]
 [139  84 143]]


In [5]:
# import numpy as np


array1 = np.array([
    [3, 5, 1],
    [2, 3, 5],
    [1, 3, 1]
])
array2 = np.array([
    [8, 5, 1],
    [2, 9, 4],
    [2, 10, 5]
])

print('Addition:')
print(array1 + array2)
print('\nSubtraction:')
print(array1 - array2)
print('\nMatrix product:')
print(array1 @ array2)

Addition:
[[11 10  2]
 [ 4 12  9]
 [ 3 13  6]]

Subtraction:
[[-5  0  0]
 [ 0 -6  1]
 [-1 -7 -4]]

Matrix product:
[[36 70 28]
 [32 87 39]
 [16 42 18]]
